# fly.toml app configuration file generated for compilador-token-ruby on 2025-11-27T14:00:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "compilador-token-ruby"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[processes]
  # ALTERAÇÃO CRUCIAL: Rackup agora confia nas variáveis de ambiente e no app.rb
  web = "bundle exec rackup" 

[http_service]
  # A porta interna aqui é 8080, que será lida pelo ENV['PORT']
  internal_port = 8080 
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  processes = ["web"]

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024