# fly.toml app configuration file generated for compilador-token-ruby on 2025-11-27T14:00:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "compilador-token-ruby"
primary_region = "gru"

[build]
  builder = "heroku/buildpacks:20"

[processes]
  web = "bundle exec rackup -p 8080 -o 0.0.0.0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  processes = ["web"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024