# fly.toml app configuration file generated for compilador-token-ruby on 2025-11-27T14:00:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "compilador-token-ruby"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[processes]
  # Certifique-se que o comando usa a nova porta
  web = "bundle exec rackup -p 4567 -o 0.0.0.0" 

[http_service]
  # A porta interna aqui DEVE ser 4567
  internal_port = 4567
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  processes = ["web"]

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024